# Generated by Django 5.1.4 on 2025-01-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0003_photo_dislikes_photo_likes_alter_photo_image_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
