# Generated by Django 5.1.4 on 2025-01-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0006_remove_photo_dislikes_remove_photo_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(default='default_tag', max_length=100),
        ),
    ]
