# Generated by Django 5.1.4 on 2025-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0007_remove_photo_tags_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photos', to='galleryapp.tag'),
        ),
    ]
