# Generated by Django 5.1.4 on 2025-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0008_remove_photo_tags_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
        migrations.AddField(
            model_name='photo',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
